### ISSUE TITLE
Telenor SIM ICCID not accepted

### ISSUE THREAD

**Issue by coderbyheart** [bifravst/sim-details#110]
https://api.sim-details.nordicsemi.cloud/2024-07-01/sim/89470060190924026052 returns 400:

```json
{
  "type": "https://github.com/bifravst/sim-details",
  "title": "Your request parameters didn't validate.",
  "invalid-params": [
    {
      "name": "iccid",
      "reason": "Not a valid issuer identifier."
    }
  ]
}
```

However, ICCID is valid:

```bash
npx e118-iin-list 89470060190924026052

{
  "iin": 894700,
  "issuerIdentifierNumber": "00",
  "countryCode": 47,
  "countryName": "Norway",
  "companyName": "Telenor AS"
}
```

**Comment by Lenakh97** [comment]
What do you want to happen in this case? That message is returned if it's not valid or if we don't support that SIM.

**Comment by coderbyheart** [comment]
Well, it is a valid ICCID.

We should return a 404 in case it's a provider where we have no usage data.
