### ISSUE TITLE
Fetch SIM card details from Wireless Logic API

### ISSUE THREAD

**Issue by coderbyheart** [bifravst/sim-details#2]
Similar to #1, but for https://simpro4.wirelesslogic.com/doc/restapi/v3

- [ ] Hardcode the limit to 4 MB until #12 is implemented.

**Comment by coderbyheart** [comment]
@Lenakh97 updated the link to the API docs, which uses client id and api key authentication.

**Comment by coderbyheart** [comment]
Hardcode the limit to 4 MB until #12 is implemented.

**Comment by Lenakh97** [comment]
Solved by https://github.com/bifravst/sim-details/pull/39 & https://github.com/bifravst/sim-details/pull/45
